from flask_sqlalchemy import SQLAlchemy
from datetime import datetime

db = SQLAlchemy()

class House(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    price = db.Column(db.Integer, nullable=False)
    date_of_transfer = db.Column(db.String(50))
    postcode = db.Column(db.String(20))
    property_type = db.Column(db.String(10))
    new_build = db.Column(db.String(5))
    duration = db.Column(db.String(20))
    paon = db.Column(db.String(200))
    saon = db.Column(db.String(200))
    street = db.Column(db.String(200))
    town_city = db.Column(db.String(100))
    full_address = db.Column(db.String(300))
    address1 = db.Column(db.String(200))
    address2 = db.Column(db.String(200))
    address3 = db.Column(db.String(200))
    current_energy_rating = db.Column(db.String(5))
    potential_energy_rating = db.Column(db.String(5))
    current_energy_efficiency = db.Column(db.Float)
    potential_energy_efficiency = db.Column(db.Float)
    built_form = db.Column(db.String(50))
    inspection_date = db.Column(db.String(50))
    local_authority = db.Column(db.String(100))
    constituency = db.Column(db.String(100))
    lodgement_date = db.Column(db.String(50))
    transaction_type = db.Column(db.String(50))
    environment_impact_current = db.Column(db.Float)
    environment_impact_potential = db.Column(db.Float)
    energy_consumption_current = db.Column(db.Float)
    energy_consumption_potential = db.Column(db.Float)
    co2_emissions_current = db.Column(db.Float)
    co2_emiss_curr_per_floor_area = db.Column(db.Float)
    co2_emissions_potential = db.Column(db.Float)
    lighting_cost_current = db.Column(db.Float)
    lighting_cost_potential = db.Column(db.Float)
    heating_cost_current = db.Column(db.Float)
    heating_cost_potential = db.Column(db.Float)
    hot_water_cost_current = db.Column(db.Float)
    hot_water_cost_potential = db.Column(db.Float)
    total_floor_area = db.Column(db.Float)
    energy_tariff = db.Column(db.String(50))
    mains_gas_flag = db.Column(db.String(5))
    floor_level = db.Column(db.String(50))
    flat_top_storey = db.Column(db.String(5))
    flat_storey_count = db.Column(db.Integer)
    main_heating_controls = db.Column(db.String(100))
    multi_glaze_proportion = db.Column(db.Float)
    glazed_type = db.Column(db.String(50))
    glazed_area = db.Column(db.String(50))
    extension_count = db.Column(db.Integer)
    number_habitable_rooms = db.Column(db.Integer)
    number_heated_rooms = db.Column(db.Integer)
    low_energy_lighting = db.Column(db.Float)
    number_open_fireplaces = db.Column(db.Integer)
    hotwater_description = db.Column(db.String(100))
    hot_water_energy_eff = db.Column(db.String(5))
    hot_water_env_eff = db.Column(db.String(5))
    floor_energy_eff = db.Column(db.String(5))
    floor_env_eff = db.Column(db.String(5))
    windows_energy_eff = db.Column(db.String(5))
    windows_env_eff = db.Column(db.String(5))
    walls_energy_eff = db.Column(db.String(5))
    walls_env_eff = db.Column(db.String(5))
    sheating_energy_eff = db.Column(db.String(5))
    sheating_env_eff = db.Column(db.String(5))
    lighting_description = db.Column(db.String(100))
    lighting_energy_eff = db.Column(db.String(5))
    lighting_env_eff = db.Column(db.String(5))
    main_fuel = db.Column(db.String(100))
    wind_turbine_count = db.Column(db.Integer)
    heat_loss_corridor = db.Column(db.String(100))
    unheated_corridor_length = db.Column(db.Float)
    floor_height = db.Column(db.Float)
    solar_water_heating_flag = db.Column(db.String(5))
    mechanical_ventilation = db.Column(db.String(50))
    address = db.Column(db.String(300))
    local_authority_label = db.Column(db.String(100))
    constituency_label = db.Column(db.String(100))
    posttown = db.Column(db.String(100))
    construction_age_band = db.Column(db.String(50))
    lodgement_datetime = db.Column(db.String(50))
    tenure = db.Column(db.String(50))
    fixed_lighting_outlets_count = db.Column(db.Integer)
    low_energy_fixed_light_count = db.Column(db.Integer)
    latitude = db.Column(db.Float)
    longitude = db.Column(db.Float)
    nearest_primary_school_distance = db.Column(db.Float)
    nearest_primary_school_ofsted_rating = db.Column(db.Integer)
    primary_school_name = db.Column(db.String(200))
    nearest_secondary_school_distance = db.Column(db.Float)
    nearest_secondary_school_ofsted_rating = db.Column(db.Integer)
    secondary_school_name = db.Column(db.String(200))
    nearest_primary_school_outstanding = db.Column(db.Boolean)
    nearest_secondary_school_outstanding = db.Column(db.Boolean)
    both_schools_outstanding = db.Column(db.Boolean)
    nearest_shop_distance = db.Column(db.Float)
    nearest_shop_name = db.Column(db.String(200))
    nearest_train_station_distance = db.Column(db.Float)
    nearest_bus_stop_distance = db.Column(db.Float)
    orig_construction = db.Column(db.String(50))
    age_in_years = db.Column(db.Integer)
    local_avg_price = db.Column(db.Integer)
    predicted_price = db.Column(db.Integer)
    ask_price = db.Column(db.Integer)

    date_created = db.Column(db.DateTime, default=datetime.utcnow)

    def __repr__(self):
        return f"<House {self.transaction_id}>"


class School(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(200), nullable=False)
    postcode = db.Column(db.String(20))
    is_primary = db.Column(db.Boolean, default=False)
    is_secondary = db.Column(db.Boolean, default=False)
    ofsted_rating = db.Column(db.String(50))
    latitude = db.Column(db.Float)
    longitude = db.Column(db.Float)
    date_created = db.Column(db.DateTime, default=datetime.utcnow)

class Shop(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    store_name = db.Column(db.String(200), nullable=False)
    size_band = db.Column(db.String(100))
    latitude = db.Column(db.Float)
    longitude = db.Column(db.Float)
    date_created = db.Column(db.DateTime, default=datetime.utcnow)

class TransportStop(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    stop_name = db.Column(db.String(200))
    stop_type = db.Column(db.String(50))  # RSE for train stations, B for bus stops
    latitude = db.Column(db.Float)
    longitude = db.Column(db.Float)
    date_created = db.Column(db.DateTime, default=datetime.utcnow)

class PostcodeLocation(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    postcode = db.Column(db.String(10), nullable=False, index=True)
    latitude = db.Column(db.Float)
    longitude = db.Column(db.Float)