from flask_sqlalchemy import SQLAlchemy
from datetime import datetime

db = SQLAlchemy()

class House(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    price = db.Column(db.Integer, nullable=False)
    date_of_transfer = db.Column(db.String(50))
    postcode = db.Column(db.String(20))
    property_type = db.Column(db.String(10))
    new_build = db.Column(db.String(5))
    duration = db.Column(db.String(20))
    paon = db.Column(db.String(200))
    saon = db.Column(db.String(200))
    street = db.Column(db.String(200))
    town_city = db.Column(db.String(100))
    fullAddress = db.Column(db.String(300))
    ADDRESS1 = db.Column(db.String(200))
    ADDRESS2 = db.Column(db.String(200))
    ADDRESS3 = db.Column(db.String(200))
    CURRENT_ENERGY_RATING = db.Column(db.String(5))
    POTENTIAL_ENERGY_RATING = db.Column(db.String(5))
    CURRENT_ENERGY_EFFICIENCY = db.Column(db.Float)
    POTENTIAL_ENERGY_EFFICIENCY = db.Column(db.Float)
    BUILT_FORM = db.Column(db.String(50))
    INSPECTION_DATE = db.Column(db.String(50))
    LOCAL_AUTHORITY = db.Column(db.String(100))
    CONSTITUENCY = db.Column(db.String(100))
    LODGEMENT_DATE = db.Column(db.String(50))
    TRANSACTION_TYPE = db.Column(db.String(50))
    ENVIRONMENT_IMPACT_CURRENT = db.Column(db.Float)
    ENVIRONMENT_IMPACT_POTENTIAL = db.Column(db.Float)
    ENERGY_CONSUMPTION_CURRENT = db.Column(db.Float)
    ENERGY_CONSUMPTION_POTENTIAL = db.Column(db.Float)
    CO2_EMISSIONS_CURRENT = db.Column(db.Float)
    CO2_EMISS_CURR_PER_FLOOR_AREA = db.Column(db.Float)
    CO2_EMISSIONS_POTENTIAL = db.Column(db.Float)
    LIGHTING_COST_CURRENT = db.Column(db.Float)
    LIGHTING_COST_POTENTIAL = db.Column(db.Float)
    HEATING_COST_CURRENT = db.Column(db.Float)
    HEATING_COST_POTENTIAL = db.Column(db.Float)
    HOT_WATER_COST_CURRENT = db.Column(db.Float)
    HOT_WATER_COST_POTENTIAL = db.Column(db.Float)
    TOTAL_FLOOR_AREA = db.Column(db.Float)
    ENERGY_TARIFF = db.Column(db.String(50))
    MAINS_GAS_FLAG = db.Column(db.String(5))
    FLOOR_LEVEL = db.Column(db.String(50))
    FLAT_TOP_STOREY = db.Column(db.String(5))
    FLAT_STOREY_COUNT = db.Column(db.Integer)
    MAIN_HEATING_CONTROLS = db.Column(db.String(100))
    MULTI_GLAZE_PROPORTION = db.Column(db.Float)
    GLAZED_TYPE = db.Column(db.String(50))
    GLAZED_AREA = db.Column(db.String(50))
    EXTENSION_COUNT = db.Column(db.Integer)
    NUMBER_HABITABLE_ROOMS = db.Column(db.Integer)
    NUMBER_HEATED_ROOMS = db.Column(db.Integer)
    LOW_ENERGY_LIGHTING = db.Column(db.Float)
    NUMBER_OPEN_FIREPLACES = db.Column(db.Integer)
    HOTWATER_DESCRIPTION = db.Column(db.String(100))
    HOT_WATER_ENERGY_EFF = db.Column(db.String(5))
    HOT_WATER_ENV_EFF = db.Column(db.String(5))
    FLOOR_ENERGY_EFF = db.Column(db.String(5))
    FLOOR_ENV_EFF = db.Column(db.String(5))
    WINDOWS_ENERGY_EFF = db.Column(db.String(5))
    WINDOWS_ENV_EFF = db.Column(db.String(5))
    WALLS_ENERGY_EFF = db.Column(db.String(5))
    WALLS_ENV_EFF = db.Column(db.String(5))
    SHEATING_ENERGY_EFF = db.Column(db.String(5))
    SHEATING_ENV_EFF = db.Column(db.String(5))
    LIGHTING_DESCRIPTION = db.Column(db.String(100))
    LIGHTING_ENERGY_EFF = db.Column(db.String(5))
    LIGHTING_ENV_EFF = db.Column(db.String(5))
    MAIN_FUEL = db.Column(db.String(100))
    WIND_TURBINE_COUNT = db.Column(db.Integer)
    HEAT_LOSS_CORRIDOR = db.Column(db.String(100))
    UNHEATED_CORRIDOR_LENGTH = db.Column(db.Float)
    FLOOR_HEIGHT = db.Column(db.Float)
    SOLAR_WATER_HEATING_FLAG = db.Column(db.String(5))
    MECHANICAL_VENTILATION = db.Column(db.String(50))
    ADDRESS = db.Column(db.String(300))
    LOCAL_AUTHORITY_LABEL = db.Column(db.String(100))
    CONSTITUENCY_LABEL = db.Column(db.String(100))
    POSTTOWN = db.Column(db.String(100))
    CONSTRUCTION_AGE_BAND = db.Column(db.String(50))
    LODGEMENT_DATETIME = db.Column(db.String(50))
    TENURE = db.Column(db.String(50))
    FIXED_LIGHTING_OUTLETS_COUNT = db.Column(db.Integer)
    LOW_ENERGY_FIXED_LIGHT_COUNT = db.Column(db.Integer)
    latitude = db.Column(db.Float)
    longitude = db.Column(db.Float)
    distance_to_london = db.Column(db.Float)
    nearest_primary_school_distance = db.Column(db.Float)
    nearest_primary_school_ofsted_rating = db.Column(db.Integer)
    primary_school_name = db.Column(db.String(200))
    nearest_secondary_school_distance = db.Column(db.Float)
    nearest_secondary_school_ofsted_rating = db.Column(db.Integer)
    secondary_school_name = db.Column(db.String(200))
    nearest_primary_school_outstanding = db.Column(db.Boolean)
    nearest_secondary_school_outstanding = db.Column(db.Boolean)
    both_schools_outstanding = db.Column(db.Boolean)
    area_code = db.Column(db.String(20))
    nearest_shop_distance = db.Column(db.Float)
    nearest_shop_name = db.Column(db.String(200))
    nearest_train_station_distance = db.Column(db.Float)
    nearest_bus_stop_distance = db.Column(db.Float)
    orig_construction = db.Column(db.String(50))
    age_in_years = db.Column(db.Integer)
    predicted_price = db.Column(db.Integer)
    ask_price = db.Column(db.Integer)

    date_created = db.Column(db.DateTime, default=datetime.utcnow)

    def __repr__(self):
        return f"<House {self.transaction_id}>"


